# Generated by Django 3.2.18 on 2023-04-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('EmailAddr', models.CharField(max_length=250)),
                ('Zipcode', models.IntegerField()),
                ('Language', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdministratorID', models.IntegerField()),
                ('RoleID', models.IntegerField()),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.IntegerField()),
                ('Type', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'AdminRoles',
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackgroundID', models.IntegerField()),
                ('HasCharges', models.BooleanField()),
                ('Charges', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Background',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainID', models.IntegerField()),
                ('ContractorID', models.IntegerField()),
                ('ServiceID', models.IntegerField()),
                ('Availability', models.BooleanField()),
            ],
            options={
                'db_table': 'Contractors',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ContractorID', models.IntegerField()),
                ('TransactionID', models.IntegerField()),
                ('Timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ServiceID', models.IntegerField()),
                ('Timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ContractorID', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('Comment', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceID', models.IntegerField()),
                ('TypeID', models.IntegerField()),
                ('Description', models.CharField(max_length=250)),
                ('Rate', models.FloatField()),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.IntegerField()),
                ('Type', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ServiceTypes',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ContractorID', models.IntegerField()),
                ('AmountPaid', models.FloatField()),
                ('Timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
