# Generated by Django 3.2.18 on 2023-04-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceZ', '0002_rename_account_accountz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accountZ',
            new_name='account',
        ),
    ]
