# Generated by Django 3.2.18 on 2023-04-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceZ', '0003_rename_accountz_account'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
