# Generated by Django 3.2.18 on 2023-04-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceZ', '0004_alter_account_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
    ]
