# Generated by Django 3.2.18 on 2023-04-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceZ', '0005_alter_account_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='person_id',
            new_name='PersonID',
        ),
    ]
